### ISSUE TITLE
不能和抖音一起用？(To be compatible with the global version of Tiktok)

### ISSUE THREAD

**Issue by wangyiwu** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#7]
![image](https://user-images.githubusercontent.com/98730380/185977116-121b41c0-1692-45e5-b410-c35ba12f93c4.png)

我没有看到 tiktok.com

**Comment by fudiwei** [comment]
> https://open.douyin.com/platform/doc?doc=docs/openapi/account-permission/douyin-get-permission-code

**Comment by wangyiwu** [comment]
> > https://open.douyin.com/platform/doc?doc=docs/openapi/account-permission/douyin-get-permission-code

I mean, Can i use this library for Tiktok, global version of Douyin

**Comment by fudiwei** [comment]
This SDK is designed to access the Douyin Open Platform API (also includes some other ByteDance's products).

I'm not sure if Tiktok has open platform API like Douyin.

If you have an official documentation, please post it.

**Comment by wangyiwu** [comment]
> This SDK is designed to access the Douyin Open Platform API (also includes some other ByteDance's products).
> 
> I'm not sure if Tiktok has open platform API like Douyin.
> 
> If you have an official documentation, please post it.

This is official doc of Tiktok global: https://developers.tiktok.com/doc/getting-started-ios-quickstart-objective-c/

**Comment by fudiwei** [comment]
Thank you very much.

It looks like the API models of requests and responses are basically the same. But I still need to take a moment to check whether just adding a new endpoint is enough. If not, I will create a new package to handle this.

**Comment by wangyiwu** [comment]
> w package to han

Thanks you very much.

**Comment by fudiwei** [comment]
Sorry for making you wait on this reply. I hope you weren’t waiting for too long.

I created a new package [SKIT.FlurlHttpClient.ByteDance.TikTokGlobal](https://www.nuget.org/packages/SKIT.FlurlHttpClient.ByteDance.TikTokGlobal/1.0.0-alpha.1) to handle this.

Because I don't have a TikTok developer account for testing, so I'm not sure it will work well. I'd like to get some feedback from you.

Unfortunately, I don't have much free time to add much documentation, especially the non-Chinese version. I'm posting sample code which should give you enough idea on how to use it.

```csharp
using SKIT.FlurlHttpClient.ByteDance.TikTokGlobal;
using SKIT.FlurlHttpClient.ByteDance.TikTokGlobal.Models;

var options = new TikTokClientOptions()
{
    ClientKey = "Your Client Key",
    ClientSecret = "Your Client Secret"
};
var client = new TikTokClient(options);

var request = new OAuthAccessTokenRequest()
{
    Code = "Your Code"
};
var response = await client.ExecuteOAuthAccessTokenAsync(request);
if (response.IsSuccessful())
{
    Console.WriteLine("AccessToken: " + response.Data.AccessToken);
}
else
{
    Console.WriteLine("ErrorCode: " + response.Data?.ErrorCode);
}
```

You can continue to leave a message here if you have more questions.

**Comment by wangyiwu** [comment]
Thanks so much. I will test it and feed back.
